### ISSUE TITLE
Question: Is native mobile app (like an app itself instead of a web) possible?

### ISSUE THREAD

**Issue by userunknown358** [ytm15/ytm15.github.io#2]
I'm not talking about tricking the original app into using the frontend (since this procedure is very difficult or is impossible to achieve) but creating the app from scratch and making it identical to the frontend

**Comment by Yacine-Book** [comment]
That would be hard for me, since I don't know much on making native apps,
but yeah with the knowledge (on how to make one) it could be possible

**Comment by userunknown358** [comment]
Fair enough

**Comment by userunknown358** [comment]
No
