### ISSUE TITLE
Suggestion: Can you also make 2014YouTube?

### ISSUE THREAD

**Issue by mrkrabs206** [ytm15/ytm15.github.io#6]
It will be based on 5.x version and uses Invidious API. Certain assets are gotten from the YouTube 5 APK and it matches the aesthetic of the 2014 app. Link will be https://ytm14.github.io/app/#. Thank you!

**Comment by ytm15** [comment]
yes, but I won't make it a separate ytm14 web-app. instead I'll add an
expflag that turns ytm15 into the 2013-2014 UI since we don't need another
ytm1(insert number here). so expect it to be coming soon

**Comment by ytm15** [comment]
yes, but I won't make it a separate web-app called ytm14. instead I'll add
an expflag that turns ytm15's UI into the 2013-2014 one since we don't need
another ytm1(insert number here), so expect the expflag to be created in
the coming days

**Comment by userunknown358** [comment]
A separate website for YTM10-19 (But 2015) is impossible because only one website can be created for each account. I don't mind if you create your own but it's not recommended as it requires a lot of coding and API grabbing.

**Comment by mrkrabs206** [comment]
Thanks y'all
