### ISSUE TITLE
ytm is down currently and watch videos on ytm15 pls fix

### ISSUE THREAD

**Issue by Pierrestro** [ytm15/ytm15.github.io#8]
ytm is down currently and watch videos on ytm15 pls fix

**Comment by Pierrestro** [comment]
![image](https://github.com/user-attachments/assets/2f5b6d89-bb61-4cfa-ba28-8a7487f6666d)

**Comment by userunknown358** [comment]
You can close the issue because the instance is back up

**Comment by Pierrestro** [comment]
> You can close the issue because the instance is back up

Thx

**Comment by baldbaldbcnb** [comment]
For me it's down

**Comment by userunknown358** [comment]
> For me it's down

This is a problem with inv.tux.pizza.
Should the owner of the frontend change the instance?
